### ISSUE TITLE
Bad link on Git Homepage (in project description)

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [adafruit/Adafruit_IO_Documentation#1]
The "Title" of the project, at the top of the GitHub page says this:
API documentation for Adafruit IO (https://io.adafruit.com/api/)

when I go to that address, it gives me a message that says:

> not found - API documentation can be found at https://io.adafruit.com/api/docs

**Comment by brentru** [comment]
Thank you for pointing this out - updated the link.
