### ISSUE TITLE
the curl request should specify the DELETE method

### ISSUE THREAD

**Issue by robertoostenveld** [adafruit/Adafruit_IO_Documentation#14]
here it explains how to delete a group. However, the curl example does not include the DELETE command and defaults to GET. 

https://github.com/adafruit/Adafruit_IO_Documentation/blob/1081503ede6c4c3fd6f0763d9b0fa33e65fdf522/source/includes/http/_groups.md.erb#L526

It should be like this:

```
curl -X DELETE -H "X-AIO-Key: xxx" ...
```

**Comment by brentru** [comment]
@robertoostenveld  Thanks for the catch - would you like to submit a pull request (https://github.com/adafruit/Adafruit_IO_Documentation/pulls)?

**Comment by robertoostenveld** [comment]
sure, will do!
