### ISSUE TITLE
Adafruit_IO.errors.RequestError: Adafruit IO request failed: 404 Not Found

### ISSUE THREAD

**Issue by vishprao** [adafruit/Adafruit_IO_Documentation#22]
import time
import serial
from Adafruit_IO import Client
aio = Client("vishprao", "aio_AETb22XvMe9r4iEbLTmrH0DoAVe0")

# ADAFRUIT_IO_USERNAME = "vishprao"
# ADAFRUIT_IO_KEY = ""

# ser = serial.Serial(
#     port='/dev/ttyUSB0',
#     baudrate = 9600,
#     parity=0,
#     stopbits=1,
#     bytesize=8,
#     timeout=1
# )
ser = serial.Serial('/dev/ttyUSB0')
while True:
	data =[]
	for index in range(0,10):
		datum = ser.read()
		data.append(datum)
		
	pmtwofive = int.from_bytes(b''.join(data[2:4]), byteorder='little') / 10
	aio.send('kingswoodtwofive', pmtwofive)
	pmten = int.from_bytes(b'',join(data[4:6]), byteorder='little') /10
	aio.send('kingswoodten', pmten)
	time.sleep(10)

**Comment by jwcooper** [comment]
Please post this on our [forums](https://forums.adafruit.com). Thanks!
