### ISSUE TITLE
can't find AIO Key on new(?) interface

### ISSUE THREAD

**Issue by Marsdrummer** [adafruit/Adafruit_IO_Documentation#43]
![image](https://github.com/adafruit/Adafruit_IO_Documentation/assets/6965245/b1f4cb74-be79-45b3-84a0-511960eb0dff)
I'm trying to find my AIO key, but it is not listed anywhere that I can find.  The left menu options that are listed here https://io.adafruit.com/api/docs/#about-the-api-docs and elsewhere are not available on my screen (see screenshot). I see Devices, Feeds, Dashboards, Actions, Power-Ups. Am I looking in the wrong place? Thanks!

**Comment by tyeth** [comment]
Top right of the screen is a Yellow Circle with black key inside, next to the New Device button

**Comment by tyeth** [comment]
Thanks @Marsdrummer for raising this. I have made a note to update the documentation for IO, I also have struggled to see the Key option in the past. There is a menu option only on smaller screens, on large displays the Yellow Key icon is top right as my screenshot showed.

https://github.com/adafruit/Adafruit_IO_Documentation/assets/6692083/2e5b545a-c0fb-4a33-a82c-3260273c3d26

**Comment by brentru** [comment]
cc @jwcooper  and @tylerdcooper

**Comment by tylerdcooper** [comment]
@brentru This is mainly an issue with out of date documentation. However, the differences between desktop and mobile is a problem that will be addressed with the future mobile updates:

![image](https://github.com/adafruit/Adafruit_IO_Documentation/assets/1672997/71c6106b-c2a3-442c-8b41-5b3f3628bf35)
