### ISSUE TITLE
access was denied to my feeds

### ISSUE THREAD

**Issue by JagadishMacharla99** [adafruit/Adafruit_IO_Documentation#9]
{"error":"not found - You are not permitted to access the feed with key 'switchfeed' belonging to embeddednani or the feed does not exist."}

**Comment by JagadishMacharla99** [comment]
So please help out to resolve this issues

**Comment by brentru** [comment]
Please visit the Adafruit IO Feedback page and click "Contact Adafruit IO Support". We'll be able to help you from there.
